Add columnValueMap option to select PhpExcel value method
robotusers/cakephp-excel pull request #4
Opened 2017-07-06 15:53 UTC by ozee31

2017-07-11 12:00 UTC, robertpustulka requested changes

2017-07-11 12:00 UTC, robertpustulka commented on src/Excel/Manager.php
> +    private function getCellValue($cell, $column, $options)
I'm following the CakePHP convention with private/protected methods, so this should be `protected`.

2017-07-11 12:03 UTC, robertpustulka commented on src/Excel/Manager.php
> +            case 'formated': return $cell->getFormattedValue();
A typo here. Should be `formatted`?

2017-07-24 12:10 UTC, robertpustulka commented
@ozee31 are you still interested in that change?

2017-08-14 09:16 UTC, ozee31 commented
I applied the requested changes

2017-08-17 11:12 UTC, robertpustulka commented
@ozee31 You need to update tests and docs as well. Test are broken now.

2017-09-04 13:43 UTC, robertpustulka commented
@ozee31 you still have some build errors:
https://travis-ci.org/robotusers/cakephp-excel/builds/265536376

2024-02-08 10:34 UTC, closed without merging